Blizzard/node-rdkafka

src/producer.cc, src/producer.h
=> Refactor ProducerMessage members and pass key to produce

src/message.cc, src/message.h, test/util/topicReadable.spec.js
added key field, using the std::string of rdkafka Message
codeveloped with @mimaison
fixes #32
=> issue#32 - Consumed message has no key

README.md
- Updated the message structure to mention the key attribute.
- Updated producer.produce() docs to mention the callback
- Updated consumer.subscribe() and consume() docs to mention the callbacks
Developed with @edoardocomar
=> Various docs updates

examples/consumer-flow.md, examples/producer.md
The consumer example uses the Flowing mode.
codeveloped with @mimaison
=> Revised consumer and producer examples

src/producer.cc
fixes issues #46 
tested on MacOS as well
=> attempted fix for key of zero length on Ubuntu 14

e2e/producer.spec.js, src/callbacks.cc, src/common.cc, src/consumer.cc, src/consumer.h, src/workers.cc, src/workers.h
=> Refactored topic_name to be 'topic' in its JS uses

lib/producer.js
allows a topic name or a Kafka.Topic to be passed to Producer.produce
=> fixes issue #58

e2e/groups.spec.js
Added tests for commit(), commitSync().
While testing committed() we found an issue (#65), so we've currently commented out the assertion.
=> Added e2e tests for consumer groups 

src/common.cc
=> Fixed ISR list in Metadata

README.md, lib/client.js
Addresses issue #68 
investigated with @mimaison
=> Document the side effect of client.getMetadata (#68)

README.md, lib/kafka-consumer.js, lib/util/topicWritable.js
=> Fix doc discrepancies with message key change

deps/librdkafka.gyp
using find with wildcards and exclusions, instead of explicit file list
=> Simplified librdkafka.gyp

e2e/both.spec.js
This verifies the fix for #36
Developed with @mimaison
=> Test coverage for null or empty message value or key (issue #36)

README.md, bench/consumer-raw-rdkafka.js, bench/consumer-subscribe.js, e2e/both.spec.js, e2e/consumer.spec.js, e2e/groups.spec.js, lib/kafka-consumer.js, src/workers.cc
Leaving this PR here for discussion as development is made on it.
=> Update consume method api to be less 'magic'

e2e/consumer.spec.js, e2e/producer.spec.js
it passes with librdkafka 0.93
=> MINOR: e2e/consumer empty assignment test neabled

e2e/producer.spec.js
if orig_broker_id is 0, then t.ok(0) will fail.
change test to t.ok(0 !== undefined) the test will pass
fixes issue #115
=> test orig_broker_id vs undefined

e2e/producer.spec.js
=> null/empty key/value not honored in delivery report

examples/consumer-flow.md
Current code in the consumer-flow example does not work
=> Fix example

examples/producer.md
=> MINOR: fix delivery report callback signature in example

lib/client.js, lib/kafka-consumer.js, src/connection.cc, src/connection.h, src/kafka-consumer.cc, src/kafka-consumer.h, src/workers.cc, src/workers.h
=> Add support for querying and getting offsets

lib/kafka-consumer.js
Also jsdoc update 
Developed with @mimaison
=> MINOR: consistently error wrap commits

README.md, lib/index.js, lib/kafka-consumer.js, src/callbacks.cc, src/callbacks.h, src/config.cc, src/config.h
=> Add support for offset commit callback

e2e/producer.spec.js, src/producer.cc, src/producer.h
=> Allow keys to be submitted as buffers

e2e/both.spec.js, e2e/consumer.spec.js
1 - modified existing e2e test so that it also checks that `offset_commit_cb` is invoked
2 - reenabled e2e test 'after assign, before consume, position should return an array without offsets'
=> Commit callback e2e test

README.md
`setInterval` takes milliseconds and not seconds I believe.
(Quite a silly change, but for someone not too familiar with JS this might cause a lot of confusion :) )
Solid work on a nodejs client btw. Good work!
=> Fix probable typo in README

README.md
I found myself digging quite long for a solution to this problem.
According to https://github.com/Blizzard/node-rdkafka/pull/170/commits/77bbb7527ba6a46cbfa455b6af6c1275cb43f498#diff-50cfa59973c04321b5da0c6da0fdf4feR441, I believe something like the above would be a correct way of calling the function.
=> Document client.queryWatermarkOffsets

src/workers.cc
=> Refactored ConsumeLoop and ConsumeNum Execute()

README.md
Forgot to add the timestamp field within the README
=> (docs) Update message structure within README

README.md
Updates Consumer example docs to reflect the message structure outlined here: https://github.com/Blizzard/node-rdkafka#message-structure
Just something small I ran into when copy/pasting from the examples.
=> Update README for Consumers

README.md
Added explanation and example about using `consumer` from Stream API
=> Example of how to get consumer from Stream API

lib/error.js
A PR for the changes as discussed at #374. There weren't any unit tests for LibrdKafkaError yet, so I left those out for now.
=> Propogate error code of Error instances used to create LibrdKafkaError, fixes #GH-374

lib/kafka-consumer.js
=> Fix the JSDoc parameter name for createReadStream

lib/kafka-consumer.js, lib/producer.js, lib/util.js, test/kafka-consumer.spec.js, test/producer.spec.js, test/util.spec.js
=> Do not modify passed config objects. Make a shallow copy instead.

e2e/both.spec.js, src/workers.cc
Modify ConsumeNum to return messages on partition EOF, to match documented behaviour of `consume(num, cb)` as described in https://github.com/Blizzard/node-rdkafka/issues/467. Regardless of confusion, this would improve latency when fully draining partitions which is the default state in non-bursty applications.
I think EOF behaviour should at least be changeable with an option, like default consume timeout is. Would also be useful to expose these in stream implementation to allow fine-tuning with it. A batch stream can be tuned quite well and the overhead isn't that big.
=>  ConsumeNum returns messages on partition EOF

index.d.ts
=> Update TS defs with AdminClient

index.d.ts
See also https://github.com/Blizzard/node-rdkafka/issues/466
=> Declare the 'unsubscribed' event

lib/producer/high-level-producer.js
Fixes issue where one always has to set serializers for HLP to work.
=> fix noopSerializer in HighLevelProducer

index.d.ts
I got some type errors when using this library - I'll try to improve types as I keep using it.
=> Improve constructor and disconnect types

README.md, index.d.ts
Follow-up to #593.
Especially the change to `index.d.ts` is quite relevant when using typescript.
=> Specify the change to the `offset.commit` event in the typings and README

src/kafka-consumer.cc
This is based on reading through the code, actually looking for something else.
The memory is allocated when converting the values in NodeAssign, and in the non-error case the ownership is transfered into the consumer's `m_partitions`, where the memory will be reclaimed in the next call to assign. For the error case however the memory isn't freed there, and it is also not freed in the caller.
This commit reshuffles the logic to only do the swapping conditionally on whether things worked out, but always free the list of partitions (either the old ones if things worked, or the non-working ones in the error case).
=> Avoid a memory leak when assigning fails

examples/producer.md
Fix a typo mistake in documentation
=> Fix producer documentation

src/producer.cc
I haven't fully tested this yet as the e2e tests fail on my machine - Kafka issue, it still failed on Node 6 without any issues, I said I'd put up the PR while I look into fixing my Kafka to test properly but if anyone can run the e2e tests to verify for me, the other tests pass fine.
This compiles on Node 6, 8, 10 and 12
=> Changes to producer file to make it compatible with Node 12

index.d.ts, lib/producer/high-level-producer.js, test/producer/high-level-producer.spec.js
This will add headers support on `HighLevelProducer` #648
=> Add headers support on HighLevelProducer

README.md
Small PR to fix a link in the README. Cheers.
=> Fix the broken configuration link in the README.md

README.md
This would have saved me a lot of pain ;)
=> DOCS: Added .setPollInterval() to Standard Producer API example

README.md, package.json
In addition to new features it fixes https://github.com/edenhill/librdkafka/issues/2363
[Release notes](https://github.com/edenhill/librdkafka/releases/tag/v1.3.0)
=> Upgrade librdkafka to 1.3.0

deps/windows-install.py
The print line was causing npm install to fail on systems with python 3
=> Fix python 3 support

src/admin.cc
The description of the `rd_kafka_queue_poll` function in the [C headers](https://github.com/edenhill/librdkafka/blob/v1.5.2/src/rdkafka.h#L4931) states that
> * @ remark Use rd_kafka_event_destroy() to free the event.
So this PR adds the missing calls of rd_kafka_event_destroy in the admin client
=> Fix memory leak in admin client

.travis.yml
for https://github.com/Blizzard/node-rdkafka/issues/873#issuecomment-783226993
=> Run travis tests in node 14 & node 15

README.md, config.d.ts, errors.d.ts, lib/error.js, package-lock.json, package.json
- https://github.com/confluentinc/librdkafka/releases/tag/v2.1.0
- https://github.com/confluentinc/librdkafka/releases/tag/v2.1.1
=> Update to librdkafka 2.1.1

package-lock.json, package.json, src/kafka-consumer.cc, src/kafka-consumer.h, src/workers.cc, src/workers.h
=> Stop consume loop thread when disconnecting

README.md, config.d.ts, errors.d.ts, lib/error.js, package-lock.json, package.json, src/binding.cc
- https://github.com/confluentinc/librdkafka/releases/tag/v2.2.0
- Remove deprecated `RdKafka::wait_destroyed` call
=> Update to librdkafka 2.2.0

.github/workflows/test.yml, package.json
- Update version to v2.18.0
- Include node 20 in tests
=> Version 2.18.0

README.md
Rebalance event was missing from the docs.
=> Add consumer rebalance event to the docs.

README.md, config.d.ts, errors.d.ts, lib/error.js, package-lock.json, package.json
- https://github.com/confluentinc/librdkafka/releases/tag/v2.5.0
=> Update to librdkafka 2.5.0

README.md
=> Update librdkafka version in readme

.github/workflows/test.yml, binding.gyp, package-lock.json, package.json, src/callbacks.cc, src/callbacks.h
Based on https://github.com/confluentinc/confluent-kafka-javascript/pull/158
Fixes #1099
=> Add support for node 23
