Blizzard/node-rdkafka

README.md
Trying to improve the first-contact experience :)
=> Update README with Requirements, CoC, and text cleanup

lib/producer.js, src/connection.cc, src/connection.h, src/errors.cc, src/errors.h, src/message.cc, src/topic.cc
=> Do native isConnected checking inside a lock (#7)

lib/client.js
It's a standard practice in node.js to have error as the first argument in a callback. If we send and object as the first argument, automatic promisification (like in [bluebird](http://bluebirdjs.com/docs/api/promise.promisify.html)) of the `disconnect` method breaks.
=> Follow standard node practice for disconnect callback

src/config.cc, src/config.h, src/connection.cc, src/connection.h, src/consumer.cc, src/producer.cc, src/producer.h
=> Properly point to topic configuration on initialization

src/workers.cc
I guess that's just a typo, but you were actually calling the function that's committing stored offsets when message was provided and function that's committing message when it actually wasn't provided. Or am I missing something here?
=> Commit the message if it's set

binding.gyp
In our setup we use docker to perform 'npm i' and to build all native dependencies in the same environment they will run in production. We maintain our own apt repository with `librdkafka@0.9.1` debian package, so we would like to build against the same version of the software as will run in production.
With this change I add a `BUILD_LIBRDKAFKA` env variable, defaulting to true, so in the default environment the behaviour of the build script would be unchanged. However, if you `export  BUILD_LIBRDKAFKA=0` before installing the package it will link to the librdkafka package installed on the machine. 
You could also benefit from this: if you install librdkafka locally and `node-gyp --BUILD_LIBRDKAFKA=0 rebuild` it will save you time on development since it will not recompile librdkafka …
=> Support building against librdkafka-dev package

README.md, src/producer.cc
- Update default partition to -1 so that use of librdkafka's default partitioner is used when one is not specified (Currently defaults to partition 0.)
- Update documentation to indicate key and partition can be specified when producing a message
=> Update Default Partition Logic. 

src/consumer.cc, src/workers.cc
Changing m_is_subscribed state on `assign` and `unassign` causes unrecoverable `RdKafka::ERR__STATE` error when consuming.
#29
=> Do not change subscribed state from assign / unassign methods (#29)

e2e/both.spec.js, lib/kafka-consumer.js, src/callbacks.cc, src/callbacks.h, src/common.cc, src/common.h, src/config.cc, src/config.h, src/connection.cc, src/connection.h, src/consumer.cc, src/consumer.h, src/message.cc, src/producer.cc, src/producer.h, src/topic.cc, src/workers.cc, src/workers.h
Rebalance callback can now be set like any other configuration value. If it is omitted, we rely on the internal `librdkafka` rebalance callback. If you set it to `true`, it will use a node implementation (and expose the event to you). If you provide a function, you will do the assignment yourself, and it will emit the event.
=> Refactor rebalance callback to more pure implementation

binding.gyp
Turns out that you can't build without sasl currently as -lsasl2 is always set in bindings.gyp, so i removed it.
As WITH_SASL=1 is the default condition and this sets -lsasl2 anyway this won't change the default behavior, but will allow WITH_SASL=0 builds to work.
=> remove -lsasl2 from default build options in bindings.gyp

bench/consumer-rdkafka.js, lib/kafka-consumer.js, lib/util/topicReadable.js, src/common.cc, src/common.h, src/consumer.cc, src/workers.cc
Currently one can use strings to pass regular expressions into subscribe but it requires knowledge of the wrapping syntax of `librdkafka`'s regular expression pattern. (i.e. `\c \"^${expression}\"`).
The update allows one to pass a v8 regular expression, e.g. `/^topic-.*/` or an array of regular expressions into subscribe and it will automatically convert it to the proper format.
=> Support passing v8 regular expressions into subscribe

cpplint.py, src/binding.h, src/callbacks.h, src/common.h, src/config.h, src/connection.h, src/consumer.h, src/errors.h, src/producer.h, src/topic.h
There're two options to build this repo controlled by the `BUILD_LIBRDKAFKA` parameter. If it's set to 1, the librdkafka sources are built from the submodule, and if it's 0, the `librdkafka-dev` package is used. In the latter case we need to point to the headers from the `librdkafka-dev` package as well, and not explicitly point to the cloned submodule. This is not only inconsistent, but it prevents us from pulling the dependency from github, since NPM doesn't do `git submodule update --init` when installing the deps, so even with `BUILD_LIBRDKAFKA=0` the build fails.
Now when we delete the explicit references to `deps/librdkafka/src-cpp/` exact location of the headers will be resolved by gyp `include_dirs` parameter.
Unfortunately, I've had to exclude the `rdkafkacpp.h` header from the …
=> Don't point to the headers in the submodule explicitly

lib/producer.js
The JSDoc should be updated after the Producer#produce was deprecated and proper way of producing is by providing `topic`, `partition`, `message` and `key` separately.
=> Updated JSDoc for Producer#produce

e2e/both.spec.js, e2e/consumer.spec.js, e2e/producer.spec.js
To help catch regressions early, we've added a bunch of new tests to the e2e suites. 
The assignment test in consumer.spec.js crashes once in a while:
```
*** ../deps/librdkafka/src/rdkafka_cgrp.c:790:rd_kafka_cgrp_partitions_fetch_start: assert: rkcg->rkcg_assigned_cnt <= (rkcg->rkcg_assignment ? rkcg->rkcg_assignment->cnt : 0) ***
Aborted (core dumped)
```
Is it because we're calling it incorrectly or is there a bug somewhere ?
=> Added a bunch of new e2e tests 

README.md, e2e/both.spec.js, e2e/producer.spec.js, lib/producer.js, src/callbacks.cc, src/callbacks.h, src/producer.cc
changed the delivery report callback API, inserted err argument before
report
dr_msg_cb configuration used as flag to copy or not the msg payload in
the delivery report
message payload not copied on the error path (see callbacks.cc TODO)
fixes #70 
committed for discussion, cleanup (eg public flag in Dispatcher TODO)
=> Added message payload in the delivery report object

lib/topic-readable.js, src/workers.cc, src/workers.h
Fixes #75 by randomising the wait interval, so for any timeout/topic activity values the contention never happens. At least it's not persistent.
=> Randomize the wait time in case the end of a partition was reached

e2e/producer.spec.js, lib/producer.js, src/connection.cc, src/topic.cc
Previously the producer was sending in a `{}` object and always creating a config. This will check if the parameter is set and only make a topic config if it is.
=> Send undefined in to leverage default config for producer.

lib/producer.js
For #68 
When providing just a topic name to the producer the new `Topic` object is created, but it doesn't honour the topic config supplied to the producer, but instead creates a `Topic` object with the default config. This default config then takes precedence over the custom config making the driver ignore the custom config.
=> Create topics with the topic config, not default config

deps/librdkafka.gyp
When loading the latest native module based on the embedded deps/librdkafka, I get an error "symbol `rd_string_render` is missing". Turns out that `rdstring.c` (the file where `rd_string_render` is defined), is not included in the current node-gyp build script. This patch just adds the file.
Alternatively, the pull request https://github.com/Blizzard/node-rdkafka/pull/56 also adds it. But as long as it is not merged, it would be nice to have at least this patch merged.
=> Add missing rdstring.c to librdkafka.gyp

lib/client.js
I have the issue that when connecting to Kafka as a producer and somehow an error occurs during connect, no callback is called.
During investigation, I found the following issue:
In `Client.prototype.connect` the state `_isConnected` is set to `true` when no error occurred during connection - so far so good. But if an error occurs, the util method `fail` is called (https://github.com/Blizzard/node-rdkafka/blob/da94b6b210fa6fad31ac51beb03cb698f7dcb8d9/lib/client.js#L184-L189). But this method is doing nothing unless `_isConnected=true` (https://github.com/Blizzard/node-rdkafka/blob/da94b6b210fa6fad31ac51beb03cb698f7dcb8d9/lib/client.js#L154) and therefor the error will not be returned to the caller.
Tbh, not sure whether the provided patch is the best fix.
=> Return error when Client.connect() fails

e2e/both.spec.js, e2e/consumer.spec.js, e2e/groups.spec.js, src/consumer.cc
The librdkafka c++ api required a vector filled with TopicPartitions. 
This is now passed after a refresh of assignments.
Added e2e tests
fixes #65 and #67
=> Fix Consumer committed() and position() API

e2e/producer.spec.js, lib/producer.js, src/callbacks.cc, src/callbacks.h, src/producer.cc, src/producer.h
This commit adds support for using opaques outside of c++ land. You can pass it arbitrary javascript objects that then can be used to correlate your message across its lifecycle.
For example:
```js
producer.produce(topic, partition, message, key, { messageId: 20 });
producer.on('delivery-report', function(err, report) {
if (err) {
return console.error(err);
}
if (report.opaque && report.opaque.messageId === 20) {
// We got our message that we sent above.
}
});
```
This allows us to get away from needing to do string/buffer comparison to potentially large payloads, and instead use a predictable, consistent way of identifying messages across delivery reports.
=> Added support for opaques to correlated messages with delivery reports

README.md, binding.gyp, deps/librdkafka.gyp
- Updated README
- Enabled the empty assignment test #63 
Do not merge as is.
It's currently pointing to the HEAD of librdkafka 0.9.3.x branch. We'll update it when the release is tagged
Work done with @edoardocomar
=> Updated librdkafka to 0.9.3:

README.md, e2e/producer.spec.js, lib/producer.js, src/producer.cc, src/producer.h, src/topic.cc, src/topic.h
This is an unfortunate solution to a potentially infrequent problem. 
When topic objects are created, they are kept in a map in the JavaScript producer object (essentially establishing handles in v8). When a producer is disconnected from, and then reconnected to, it will try to use the  existing topic handles in the map. However, topics are bound to `RdKafka::Handle`, which is destroyed on disconnect. 
We could make it clear the cache of created topics on disconnect, but that means disconnect is now going to wait on the garbage collector to remove the topics before the handle will release. We definitely don't want to block that long, or potentially forever, because we are relying on the GC.
We can make hooks between both objects - topic and handle - so they can be notified of changes. …
=> Change topics to be destroyed on use, or take a string

lib/topic-readable.js, test/topic-readable.spec.js
The callback is called on the `'close'` event – while the code emitted a `'closed'` one. I chose to stick with the former one, as it is what standard readables emit.
=> Closing the TopicReadable calls the callback

e2e/both.spec.js, e2e/consumer.spec.js
Resubmitting this to add the commit tests. I am afraid they will not play nice with other tests as they leave a `consumer.once()` untriggered... if you think that's ok let me know.
I'll push the changes to meet the new API for commitMessage() in a few
=> Tests for commit behavior

e2e/consumer.spec.js, lib/kafka-consumer.js
It used to return error objects instead.
This seems to me the better API – but might be breaking some code. Personally I was surprised by this behavior and had a bug that assumed that because the commitSync did not throw.
@webmakersteve there are a couple of other issues with commit / commitSync that I want to look at / work on, would you prefer separate PRs?
=> commitSync throws errors as they happen

lib/client.js, lib/kafka-consumer.js, lib/producer.js
Error event is unnecessary as callbacks will pass the error forward. If the user does not care about the error, they would not specify the callback.
An error event should be saved for fatal type errors that `librdkafka` would not recover from ordinarily. There are essentially none of these situations currently (as far as I know).
=> Remove error event from non-stream implementations

e2e/both.spec.js, e2e/consumer.spec.js, e2e/groups.spec.js, lib/kafka-consumer.js, src/consumer.cc, src/consumer.h, src/workers.cc, src/workers.h, test/mocha.opts
Previously it used a v8 worker to spin up and do the commit, but the refactor has it use the async method provided in the library. It currently does not take a callback.
Synchronous methods are still available and behave as they did previously.
=> Refactor async commit to use internal async method

README.md
Add in timestamp and opaque parameters to REAME docs for
producer.produce() to match code https://github.com/Blizzard/node-rdkafka/blob/48c026e7f086f7f3592ddcf89e75b8fb48290f99/lib/producer.js#L204
=> Document producer timestamp and opaque parameters in README

deps/librdkafka.gyp
Works with both librdkafka 0.9.5 and current master where new sasl files
need to be compiled.
Conditional for win32, but tested on macOS not Windows
=> Updated gyp file for both librdkafka 0.9.5 and 0.11

examples/consumer.md
... such as a missing or typo on `group.id`, which it just quit silently now
=> Make consumer example more verbose on config error

README.md
`dr_msg_db` causes an error; should be `dr_msg_cb`.
=> Fix delivery-report dr_msg_cb flag

README.md
The instructions for running unit tests include the `make` target, but the instructions for running integration tests do not.
=> Update instructions on running integration tests

lib/client.js
Small bug found while using the repo :) Please see below block for error message
```
/Users/philipyoo/Scality/wip/blizzard-kafka/node_modules/node-rdkafka/lib/client.js:243
return Date.now() - this.metrics.connectionOpened();
^
TypeError: this.metrics.connectionOpened is not a function
```
=> Fix Client.connectedTime method

binding.gyp, deps/librdkafka.gyp, src/workers.cc, src/workers.h
Do not merge yet. Still needs conditional adjustments based on architecture and debug/release.
=> Windows support

binding.gyp, configure, deps/librdkafka.gyp, package.json, util/configure.js, util/get-env.js, util/has-lib.js, util/librdkafka-config-checker.js
Rather than relying on users to specify that they have SASL, we can use
librdkafka's built in checking to find out. If we parse out the header
file that is made we can export environment variables so node-gyp can
configure itself appropriately.
This commit should also improve development because configure is now run
at install time only. It means when developing you do not need to
recompile the entirety of librdkafka with each minor change
=> Refactor configure step for compilation

README.md, deps/librdkafka.gyp
Execute `nuget restore` before we build the `librdkafka` project, so that windows users will have the required `nuget` dependencies for the build. Improves #248 and should hopefully be enough to close #45
=> Improve Windows Build

lib/kafka-consumer.js, src/common.cc
As with Kafka brokers >=0.10.0 support timestamping of events it would be nice to have that field available.
=> Add the message timestamp to the consumer payload

lib/producer-stream.js, test/producer-stream.spec.js
Experienced by myself and as reported by #294, a `ProducerStream` in `objectMode` being drained throws an error: `'topic' == undefined`.
I managed to add a test case that reproduces this issue. After adding another for a streams not in `objectMode` to make sure we don't regress, I implemented a simple fix, getting both tests to pass.
I'm new to the codebase and open to any suggestions for a different approach 😄 .
=> Fix draining of ProducerStream in object mode

lib/client.js
if getMetadata call fails, client disconnects itself silently. add a disconnect event so I can call connect again to reconnect.
=> emit disconnected event on connect failure

index.d.ts
Producer actually extends from WriteStream and consumer extends from ReadStream.
=> Fix ProducerStream and ConsumerStream types

index.d.ts
Added return types for:
connect
disconnect
getMetadata
queryWatermarkOffsets
For tsc to work properly if node-rdkafka is included in a project as a dependency
=> Additional return types

index.d.ts
Added a new interface to the definition file to allow typings on
messages received via the consumer stream API for example.
```typescript
stream.on('data', (message: Kafka.ConsumerStreamMessage) => {
console.log('Got message');
console.log(message.value.toString());
});
```
=> Add typescript interface for consumer stream api messages

src/producer.cc
@webmakersteve I was trying to use `queryWatermarkOffsets` on `producer` and it was erroring out.
=> Add missing producer method

lib/kafka-consumer-stream.js
As with #344, I ran into an issue with the `KafkaConsumer` reference being lost from the `KafkaConsumerStream` after closing the stream while it's reading at a high rate. 
Through the asynchronous nature of a `Stream`, it's possible there's some left to read even if the underlying consumer has been disconnected. A call in the `_read` methods to check whether the consumer is connected throws an error, as the consumer was set to null.
I don't believe that removing the reference does anything in the first place? Happy to be made of aware of anything, so I can help mitigate it some other way.
=> Prevent KafkaConsumerStream from losing it's KafkaConsumer reference

lib/producer-stream.js, test/producer-stream.spec.js
Mirroring the behaviour of the `ConsumerStream`, this adds the ability to forward connection options when creating a ProducerStream. Very useful when trying to control the client's `timeout` option, amongst other things.
I added a simple test verifying the option is being passed down from the constructor. I'm happy to make any other changes if required.
=> Accept `connectOptions` with ProducerStream constructor

src/workers.cc
-  Clarify that the function retrieves several messages,
as opposed to getting "the number" of a message.
Signed-off-by: Sven-Thorsten Dietrich <thebigcorporation@gmail.com>
=> Grammar fix: plural messages

binding.gyp
Build system links against system `librdkafka.so` even though it builds its own `librdkafka.so`.
This causes segfault when system librdkafka is built against different version of OpenSSL (often 1.1) than node's OpenSSL (1.0).
This fixes #372 for me.
=> Link against built librdkafka.so, not the system librdkafka

index.d.ts
Previously only supported the non-flowing option and would complain
that arguments were missing.
This allows TS to compile when using flowing mode
=> Add typescript definition overload for both consumer modes.

binding.gyp
Add librdkafkacpp.lib to additional dependencies and update how the linker looks for libraries on windows. Solves [#389](https://github.com/Blizzard/node-rdkafka/issues/389).
=> Fix the build on windows

lib/producer-stream.js, test/producer-stream.spec.js
While the `librdkafka's` queue is full, trying to produce a message throws `Error: Local: Queue full`. This means the stream should backoff for a while, do a poll (things like delivery reports count towards the queue, fetching them might clear it up), and try again shortly after. Basically implementing backpressure, allowing Node streams to buffer messages.
This **is** implemented for writing a single message at the time, however, was missing for writing multiple chunks at once (when the stream is drained). I wrote tests to confirm this bug and then implemented a fix.
I'm happy to make any tweaks or additions if that's necessary, just let me know!
=> Handle queuing errors when draining the ProducerStream

src/common.cc
Allocate memory using Nan::Encode to ensure handle garbage collection frees it as expected.
=> Fix memory leak in ToV8Object

binding.gyp, deps/librdkafka.gyp
Here's me taking a stab at getting relative path builds working in the linux environment in response to portability issues brought up in https://github.com/Blizzard/node-rdkafka/issues/405
This was mostly implemented though guess and check, so I am more than open to feedback. I got rid of every instance of `<(module_root_dir)/` except for the one in the `include` (which I couldn't get to pass without it).
I'm not sure which paths could be absolute, which need to be relative, but I wanted to get the ball rolling so I converted everything I could.
The mac build we'll have to iterate on with travis since I only have access to a linux environment
=> feat: Using relative paths in builds

README.md
A couple of days ago [v0.11.5 was released](https://github.com/edenhill/librdkafka/releases/tag/v0.11.5). Most notably, it brings support for [KIP-4](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations) (the Admin API), but also a list of bug fixes.
=> Migrate to v0.11.5

src/kafka-consumer.cc
I ran into this limitation while trying to use `consumer.pause` with a `KafkaConsumer` that isn't subscribed to a Consumer Group, but assigned toppars manually. In neither rdkafka's or the original Java implementation and documentation can I find anything to suggest that this should prevent the use of these control flow methods, but I'm happy to hear what I'm missing :)
=> Don't require KafkaConsumer to be subscribed to pause and resume the consumption of toppars

README.md
The previous link was a bit outdated, adjust it to match the librdkafka version exactly.
Note that instead of pointing to the specific version one could also point to https://github.com/edenhill/librdkafka/blob/0.11.x/CONFIGURATION.md, but that would risk documenting options that wouldn't be available yet in node-rdkafka.
=> Point to the correct CONFIGURATION.md

Makefile, README.md, package.json, src/admin.cc, src/admin.h, src/common.cc, src/workers.cc
- `npm audit` reports security issues with mocha 2.x. I used `npm audit fix --force` to update the `package.json` file automatically.
However since mocha 4, `process.exit()` is not called automatically and `make e2e` was not terminating once all tests had passed. So it looks like some resources are not currently closed properly. It's something we should fix but in the meantime I've added the `--exit` flag to force the previous behavior (https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit).
- `make lint` also has a number of issues and I fixed the low hanging fruits.
- Minor code/README fixes
=> Updated mocha + small code changes for cpplint

lib/client.js
Currently emitting `self.metrics` which is an empty object before the connection has been created and gobbling the librdkafka error, so it's pretty useless for figuring out what happened.
=> connection.failure error emit

src/admin.cc
On failing to create a Topic or adding partitions, if the broker returns an error message,
this is now passed back into the JS error.
fixes https://github.com/Blizzard/node-rdkafka/issues/538
note : currently `librdkafka` is returning a fixed error message when create partitions fails,
that will being fixed with a separate PR to `librdkafka` see https://github.com/edenhill/librdkafka/issues/2154
Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
=> Return broker error messages for create topic, create partitions

index.d.ts
Hey,
The current event emitter declaration is 
```typescript
// currently need to overload signature for different callback arities because of https://github.com/Microsoft/TypeScript/issues/15972
on<T extends keyof EventCallbackRepositoryArityOne, K extends EventCallbackRepositoryArityOne[T]>(val: T, listener: (arg: K) => void): this;
on<T extends keyof EventCallbackRepositoryArityTwo, K extends EventCallbackRepositoryArityTwo[T]>(val: T, listener: (arg0: K[0], arg1: K[1]) => void): this;
once<T extends keyof EventCallbackRepositoryArityOne, K extends EventCallbackRepositoryArityOne[T]>(val: T, listener: (arg: K) => void): this;
once<T extends keyof EventCallbackRepositoryArityTwo, K extends EventCallbackRepositoryArityTwo[T]>(val: T, listener: (arg0: K[0], arg1: K[1]) => void): this;
``` …
=> Changed index.d.ts event emitter keys

lib/error.js
While testing the new AdminClient features (very cool btw!) I noticed node-rdkafka was missing the `ERR_TOPIC_ALREADY_EXISTS` error code.
Upon closer inspection, it looks like error codes were not updated when we moved to librdkafka 0.11.5.
To use error codes in JS, we have to use `Kafka.CODES.ERRORS.ERR_TOPIC_ALREADY_EXISTS`. I wonder if we could have a shortcut that drops one of the middle bits `CODES` or `ERRORS`. Still it's better than using the error numbers directly!
=> Added missing librdkafka error codes

README.md, package.json
Looking through the changes this should be a fairly small update. There is a version 1.0.0 on the horizon; I think it makes sense to produce one last release with this version, as there seem to be quite a lot of changes in 1.0.0.
Note: I'm still in the process of actually testing this version, and we do not have a Windows environment so I just bumped the version in package.json and checked that that nuget package seems to be available.
=> Update librdkafka to 0.11.6

index.d.ts
The `static` modifier was missing so typescript was throwing a not found error when trying to use it as a factory method.
```
AdminClient.create()
```
=> Correct type definition for AdminClient.create

README.md, index.d.ts
The _event_ only receives the topic partitions, although it will also get called when an error has occurred (see https://github.com/Blizzard/node-rdkafka/blob/56c31c4e81f2a042666160338ad65dc4f8f2d87e/lib/kafka-consumer.js#L93-L104). This PR goes to assume that the implementation is correct and the documentation is wrong, and then fixes the documentation. I guess another way of looking at the same problem is to say the documentation was correct, but the implementation isn't right now, and should be fixed to produce the two arguments (similar to the way the rebalancing is handled). That would introduce a backwards-incompatible change. Let me know if that makes more sense, and I can update this PR accordingly.
While there: the event is missing in `index.d.ts`. That change depends on the …
=> `offset.commit` event documentation and implementation do not match

lib/producer.js
When disconnecting a producer, if an poll interval was set, there was a new call `self.setPollInterval(interval)`.
But on this new call there is a check `if (!this._isConnected)`. If it is not connected, a new listener will be bound on the "ready" event. This can happen because the flag `_isConnected` is also changed on the event "disconnect". Sometimes, the `setPollInterval` "disconnect" listener will be triggered first, and thus a new function will be bound on "ready".
I believe we should instead clear everything on "disconnect" and not risk biding listeners, so in this change I call `self.setPollInterval(0);` which should clear any interval.
Related discussion: https://github.com/Blizzard/node-rdkafka/issues/395
=> Remove poll interval on disconnect

src/callbacks.cc, src/callbacks.h, src/config.cc, util/test-producer-delivery.js
Fixes issue 553 by batching delivery report in up to 100 deliveries per `DeliveryReportDispatcher::Flush()`. Each `DeliveryReportDispatcher::Flush()` now takes a maximum of about 500 microseconds with an empty callback in a 3GHz core. If there are remaining delivery reports, then Flush() will request a further callback. Test is included in util/test-producer-delivery.js
- Avoid a copy construction of the DeliveryReport in the for loop by using const-references. This, in turn, avoid dynamically allocating the two strings per delivery report. 
- Delivery only requests a callback when the outstanding delivery reports is 1. There is no need to keep requesting the callback if it has already been requested.
- Fixes an issue I encountered where the debug build of node-rdkafka was throwing an …
=> Issue-553: Fixes delivery report performance issue

index.d.ts
Adds TypeScript type declarations for the newly added `HighLevelProducer` which were missing.
=> Add type declarations for HighLevelProducer

src/callbacks.cc
On Windows 10 with windows-build-tools I receive
```
..\src\callbacks.cc(275): error C2589: '(': illegal token on right side of '::' [C:\www\htdocs\cust\wt\kafka\apps\packages\node-rdkafka\build\node-librdkafka.vcxproj]
..\src\callbacks.cc(275): error C2059: syntax error: '::' [C:\www\htdocs\cust\wt\kafka\apps\packages\node-rdkafka\build\node-librdkafka.vcxproj]
```
This appears to be due to macros elsewhere redefining `min`. Making the type explicit solves the problem and compiles just fine.
=> Update for Windows

e2e/both.spec.js, lib/kafka-consumer.js
Without the err information, the emit event is completely useless as one does not know whether it succeeded or failed, and had to use the callback function.
This is a breaking API change, but follows the convention `(err,data)` used for other events.
Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
=> Emit also the error code in the offset.commit event

README.md, deps/windows-install.py
The latest _librdkafka_ `1.0.0` has additional dependency `libzstd.dll` that must be included with the Windows build. Thanks to @edenhill it also includes `msvcp120.dll` out of the box so installing VS Build Tools 2013 is no more the requirement (refs #493 and librdkafka [#2103](https://github.com/edenhill/librdkafka/issues/2103)).
This PR assumes that #585 will be merged first.
Also ref #579.
=> Fix Windows build for librdkafka 1.0.0+

.travis.yml, Makefile, README.md, binding.gyp, deps/windows-install.py, test/producer/high-level-producer.spec.js, win_install.bat
I think there are some mistakes about travis-ci :
First, the item of `matrix.include` can only specify one version of node. If multiple given, only the first one will been processed.
Second, the original travis-ci config mixes the test script with deploy script. I think it will be more clear if we separate each other.
Since the reasons mentioned above, I dropped the use of `matrix.include`,  used `jobs.include` instead. There are 4 stages defined in yml file, its names are `test_on_mac` `test_on_win` `create_doc` `publish_num`. The default stage `test` is not specified in yml file, but will also been triggered, and been run on multiple node versions. 
At the end, I add the support of building on windows. Someone said that the building was broken on windows, and now we can test on windows …
=> Enhance the travis-ci script

README.md, package.json
This PR bumps the `librdkafka` version to 1.1.0, release notes are here: https://github.com/edenhill/librdkafka/releases/tag/v1.1.0
I'm not sure if we just want to bump or perhaps make appropriate changes to match new configuration properties as of 1.1.0.
✌️
=> Update librdkafka to 1.1.0

binding.gyp
From: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html
The hard-coded paths for the linux linked build cannot be exploited with AWS Lambda's Layers style of building dependencies into a deployable asset.
If one was to create a layer they'd need to install `librdkafka` and set the prefix-path as `./configure --prefix="/opt"` which would result in `/opt/includes/librdkafka` having the header files. 
I've just added this to the array for now so we could potentially consume/publish as a part of an AWS StepFunctions or Lambda heavy workflow.
Happy to discuss - feels like there's a better solution to acquire the includepaths out there somewhere.
=> Allow compatibility with AWS Lambda Layers

index.d.ts
It's missing the headers parameter, which means if you want to send headers using
`node-rdkafka` from TypeScript, you have to any-cast the producer, or extend w/
your own typings.
=> Update Producer.produce TypeScript signature

README.md, package.json
Upgrading to using librdkafka 1.2.0. There are some consumer performance enhancements that would be good to get into mainline node-rdkafka.
[Release notes](https://github.com/edenhill/librdkafka/releases/tag/v1.2.0)
=> Updating to librdkafka 1.2.1

.travis.yml, src/kafka-consumer.cc
Refactoring .travis.yml and Makefile caused regression in #609,
which no longer stops the build if previous lint or test step with
make fails.
=> Stop the build with error if lint step fails

index.d.ts
Update TypeScript type declaration file to include definiton of
Prouder.createWriteStream method.
Fixes: https://github.com/Blizzard/node-rdkafka/issues/724
=> Add type for Producer.createWriteStream

index.d.ts
See #717 for the conversation as to why this alias `type` was picked.
=> Update "key" Typescript Type

index.d.ts
Package wont be able to compile with ts due to changes in DefinitelyTyped/DefinitelyTyped#40927
Up version after merge pls. This is very critical.
-------
Fix error with EventEmitter caused by DefinitelyTyped/DefinitelyTyped#40927
Add type for KafkaConsumer.createReadStream
Fix return type for Producer.createWriteStream
=> index.d.ts broken

index.d.ts
Adds this missing definition from the `KafkaConsumer` API: https://github.com/Blizzard/node-rdkafka/blob/50ca65778c2295a690683857aa84522639be87a2/lib/kafka-consumer.js#L158
=> add createReadStream to KafkaConsumer type def

deps/windows-install.py
When installing node-rdkafka on Windows, if `python` on your PATH points to python 3, the installation fails with an error about being unable to import urllib2. This PR changes the installation script so it tries to import the python 3 module first, and fall back on the python 2 module. This will allow installation regardless of the python version you have as your default.
=> Add support for python 2 and 3 when installing on Windows

index.d.ts
It utilizes a script that
- pulls content from librdkafka/CONFIGURATION.md
- converts that to TypeScript interfaces
A few interesting things that deviate from librdkafka/CONFIGURATION.md
- `dr_msg_cb` - becomes `'boolean'
- `dr_cb` - becomes `'boolean | Function'
- `rebalance_cb` - becomes `'boolean | Function'
- `offset_commit_cb` - becomes `'boolean | Function'
- I'm using 4 spaces as opposed to the 2 space guideline to match with the existing spacing in this file
- The script that pulls from librdkafka documentation - https://gist.github.com/ntgn81/066c2c8ec5b4238f85d1e9168a04e3fb. I could put it as part of this repo, if that is okay
=> Add TypeScript defs for Producer/Consumer config

.travis.yml, src/admin.cc, src/binding.cc, src/callbacks.cc, src/common.cc, src/config.cc, src/errors.cc, src/kafka-consumer.cc, src/producer.cc, src/topic.cc, src/workers.cc
Builds and passes tests on Ubuntu with 13.x.                                     
Also fixes many deprecations.  A few outstanding deprecations related to         
integrating with the new async context tracking API remain, so                   
continuation-local-storage may (still) not work (have not checked).              
Fixes: https://github.com/Blizzard/node-rdkafka/issues/733 
-----
This was a fairly mechanical fix, I'm not that familiar with the code or usage.
I noticed that `npm test` is passing but `make`  is not, which concerned me, but it turns out the same is true for master. So, I'm still concerned :-), but it isn't a problem intoduced by this PR AFAICT.
=> Support Node.js 13.x 

e2e/both.spec.js, src/producer.cc
When [accessing data](https://github.com/nodejs/node/blob/v13.x/src/node_buffer.cc#L219) from empty string Buffer `Buffer.from("")` in Node v13, it returns `NULL` instead of pointer.
Consequence to this is that key/value is written as `NULL` which is wrong.
Refs #36, #759, https://github.com/nodejs/node/issues/32089
=> Empty string value/key shouldn't be treated as null

README.md
OpenSSL 1.0.2 is EOL, as is 1.1.0. Node.js 10.x and later use OpenSSL
1.1.1. Distros might choose to compile and link their custom builds of
10.x against 1.1.0, but 12.x and later don't support older than 1.1.1.
Also, given that Node.js exports the OpenSSL symbols to bindings, it
would be unwise for a binding to use a version of OpenSSL _other_ than
that used by the Node.js the binding is built against.
All of which is to say... its hard to specify exactly what version of
OpenSSL should be used, but it definitely is no longer 1.0.2.
=> Update required OpenSSL version

index.d.ts
This PR updates TypeScript typings:
- Renames InternalAdminClient to IAdminClient
- Exports IAdminClient
=> Expose AdminClient interface (#777)

index.d.ts
I have a consumer/producer that is implemented on top of these `ConsumerStream` and `ProducerStream` and before this commit (https://github.com/Blizzard/node-rdkafka/commit/66d53834e33c8cb1cfdc1d2d31b5eae851b3841a) they were both being exported.
It would be nice to have typings for this interface and not have to use `any`.
=> Expose ConsumerStream and ProducerStream interfaces

lib/client.js, lib/producer.js, src/callbacks.cc, src/callbacks.h, src/config.cc, src/config.h, src/connection.cc, src/connection.h, src/kafka-consumer.cc, src/producer.cc, src/producer.h, test/binding.spec.js, test/consumer.spec.js
To dispatch internal events library persists their JavaScript callbacks in the underlying native code. These persistent callbacks disable garbage collection of their holding consumer or producer instance.
One approach to fix this issue is to implement some sort of `destroy()` method that would clean up those persistent callbacks but this doesn't feel natural in JavaScript.
A more natural approach is to wire up and persist those callbacks right before `connect()` call and to clean them up right after `disconnect()` call which is exactly what this PR is all about. This also enables instances re-usability so users can `connect` and `disconnect` as many times as they want and the instance will remain garbage collectible. Callbacks still have to be persisted but this time inside JavaScript …
=> Fix producer/consumer memory leaks #731

src/binding.cc
22452f83 introduced bad syntax
#ifdef NODE_MAJOR_VERSION <= 8
That's not valid, I'm not sure why I didn't notice the compiler warning,
but this fixes it. Its possible that nobody tried to use node-rdkafka
with Node.js <= 8.x yet.
=> Fix C preprocessor syntax error affecting node 8.x

package.json
Note that this is _not_ necessary for package _users_. Its a dev
dependency, but v5.x is the version that comes with current npm
releases, I suggest this package should track that. Note that 3.x is
quite old, and misses numerous bug fixes, so isn't going to work on lots
of systems, particularly Python 3 systems.
=> Update dev dep: node-gyp to v5.x

lib/kafka-consumer.js
These errors weren't properly being wrapped as `LibrdKafkaError`s, and were thus being emitted as [raw error codes](https://github.com/jpdstan/node-rdkafka/blob/c63ef5cd9f5983d572b1d959018d7b2e1ffd34aa/src/callbacks.h#L248) instead of error objects, as we expect in every other error callback on kafka events.
=> fix: wrap offset.commit errors with LibrdKafkaError

e2e/both.spec.js
In the afterEach part maybeDone is defined to take 1 `err` argument but it is called with 0.
=> maybeDone missing argument added

lib/kafka-consumer.js, src/kafka-consumer.cc, src/workers.cc, src/workers.h
The pull request is aimed to resolve the issue of https://github.com/Blizzard/node-rdkafka/issues/709 .
=> When the consumer read timeout, try to read after the value of `timeout`

README.md, deps/windows-install.py
In Windows ,the download of the library of librdkafka may be so slowly, especially when you are in China. It may cost a long time to  download it. Sometime I have to wait for several hours. 
So I add an feature of reading the download url from environment variable.
=> Read the download url of librdkafka from Windows environment variable

e2e/both.spec.js
Found while working on #803 and wondering why a regression I put there didn't lead to this test failing.
The regression I put there was removing the `if` condition in https://github.com/Blizzard/node-rdkafka/blob/master/src/workers.cc#L537-L539. Then I expected `consume` to directly return, but of cause it still waits for `fetch.max.wait.ms` as we only get EOF notifications at the end of the `fetch` call. Took me some time to figure that out 😂 .
Note that the heuristic of terminating the loop when seeing an `EOF` message is anyway not the best heuristic, really we should wait until we've seen `EOF` messages from _all_ partitions that are consumed, only in cases where we're only assigned to one partition is this the same. But this is beyond this PR.
=> Improve 'should return ready messages on partition EOF' e2e test

README.md, e2e/both.spec.js, lib/kafka-consumer.js, src/workers.cc, src/workers.h
This PR should handle the consumer topic errors (#863) that are right now making a breaking change in the "flowing mode" consumer.
More info:
https://github.com/edenhill/librdkafka/issues/1540
https://github.com/edenhill/librdkafka/wiki/Proposal:-Consumer-topic-error-handling
=> Handle consumer topic errors in librdkafka v1.5.0+ (#863)

index.d.ts
The use of chained `extends` statements in the `EventListener` type generic results in a very deep type instantiation for the listener function.
If the listener callback also utilizes generics, Typescript will complain that `Type instantiation is excessively deep and possibly infinite.ts(2589)`
The depth that the `EventListener` generic is taking up can be reduced to a single level by using a type map with the `keyof` keyword.
=> Reduce event listener type instantiation depth

README.md, config.d.ts, errors.d.ts, lib/error.js, package.json
I tried to look at some recent similiar procedure how this is done (like in https://github.com/Blizzard/node-rdkafka/commit/6810bdb9369e331170d248f5acc5cfb7517f4891#).
I executed tests (all succeeded) and e2e tests. They always succeed the second time, but the Consumer/Producer, "should be able to produce, consume messages, read position: subscribe/consumeOnce" usually fails the first time (when the topic  doesn't exist yet), because the consumer emits a "Broker: Unknown topic or partition" error (error code 3) which leads to a `length` can't be called on `undefined` error. I think this is a regression already introduced by the update to librdkafka 1.5.0, so not a regression here. As the update description from 1.5.0 says:
> Subscribing to non-existent and unauthorized topics will now …
=> Update librdkafka from 1.5.3 -> 1.6.1

.travis.yml, binding.gyp
=> Use C++14 to be able to build using node v16.x

lib/admin.js, src/admin.cc
The timeout_ms parameter for the admin APIs wasn't being used anywhere.
With that change, the parameter is now used to determine how many times we are going to poll for the given event.
I didn't change the polling timeout (1000ms) so I had to make a decision to round down to the second (i.e. 1800ms would be rounded down to 1sec) and also overriding any value < 1000 to 1000.
Since that parameter wasn't being used yet, another solution would be to change the granularity from ms to sec in the function (timeout_sec instead of timeout_ms). This would prevent the rounding down and the minimum value tricks.
=> Fix bug where the timeout in the admin APIs wasn't taken into account.

Makefile, e2e/admin.spec.js, e2e/both.spec.js, e2e/consumer.spec.js, e2e/groups.spec.js, e2e/producer-transaction.spec.js, e2e/producer.spec.js
This commit helps to run integration tests in different environments
other than localhost kafka.
It also helps by cleaning up the integration tests a bit.
=> Simplify e2e tests removing random timeout values

src/producer.cc
When there is an error trying to produce() messages,
no delivery report is ever generated for the message.
If the user specified `opaque` data for the message,
the call to produce() will have "pinned" it, but with
no delivery report, it is never released.  This change
checks for this condition and releases the opaque
data when this happens.
Fixes: #953
=> fix: release opaque data on error in produce

src/workers.cc
In KafkaConsumerConsumeNum, we forget errors when we've already seen some messages,
because we can only return an error or messages, and the messages are more important.
Additionally, the error could be re-fetched when fetching another time at the higher offset, as no
new messages will be available then and the error will thus be returned.
This logic breaks when returning EOFs: EOFs will be returned even if we're at the end of a partition.
But it's still important to see errors, and arguably it's more important.
So, if we've only seen EOFs so far, we should return the error when encountering one.
This would help us in receiving OffsetOutOfRange errors, which is important for us to detect.
=> Report error instead of returning EOFs when no other messages have been seen so far in KafkaConsumerConsumeNum

examples/docker-alpine.md
Fixes the Alpine example, which [removed](https://git.alpinelinux.org/aports/commit/?h=3.12-stable&id=5ad0ec7da1064361cc74d56edf7524960f49ef9b) the generic `python` package in v3.12.
node-gyp supports python3 since v5.x:
https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md
=> Docs: fix alpine example due to python version

.github/workflows/npm-publish.yml, .github/workflows/test.yml, .gitignore, CONTRIBUTING.md, Makefile, README.md, binding.gyp, package-lock.json, package.json
- Update test workflow to use node versions 14, 16, 18, 19
- Add support for node 19
- Update mocha, node-gyp, and nan
- Update node engine requirement to >= 14
- Remove shrinkwrap file - replace it with package lock
- Document how to publish new package versions
- Use node version 18 when publishing
=> Update dependencies & workflows

.github/workflows/test.yml, package-lock.json, package.json
Reverting node engine change. The engine requirement should only be updated in a major version
Fixes #999
=> Revert node engine change

CONTRIBUTING.md, README.md, config.d.ts, errors.d.ts, lib/error.js, package-lock.json, package.json
Submodule updated to point towards https://github.com/confluentinc/librdkafka/releases/tag/v2.3.0
=> Update to librdkafka 2.3.0

.gitignore, CONTRIBUTING.md
I've spend quite a bit of time to figure out why the repo wasn't working on my machine, before I realized I needed to init the git submodule. In hindsight, it was very obvious, because that submodule is the point of this entire repo. Nevertheless it would have helped a lot to have these instructions.
Also, i use IntelliJ, so i've added `.idea` to the gitignore.
=> docs: simplify contributing by adding instructions

index.d.ts
In the typings KafkaConsumer incorrectly requires that commitSync be called with a TopicPartitionOffset or an array of TopicPartitionOffsets, when docs say that null can be passed to commit all read offsets. This change allows null to be passed without resorting to hacks like `client.commitSync(null as any)`.
=> Allow passing null to commitSync in KafkaConsumer typings

index.d.ts
Without exported event types, they must be duplicated in dependant code to correctly use the abstract `Client` class, which is needed when either a Producer or Consumer client could be the value of a class field. If no events are supplied to the `Client` class, then subscribing to event listeners doesn't work. When these types are duplicated in the dependant code and passed like `_client?: Client<KafkaProducerEvents | KafkaConsumerEvents>`, the event listener typings work correctly. 
Exporting these types is the least effort to enable this usecase, otherwise requiring larger changes to how the abstract class is typed. One cannot say `_client?: KafkaConsumer | Producer` because then the event listener functions have conflicting types and cannot be used at all.
=> Export event types for use with abstract Client class

e2e/both.spec.js, e2e/consumer.spec.js, index.d.ts, lib/kafka-consumer.js, src/connection.cc, src/connection.h, src/kafka-consumer.cc, src/kafka-consumer.h, src/producer.cc
The purpose of these changes is to add a functional version of node-rdkafka that supports incremental cooperative rebalancing. Given that librdkafka has supported this type of rebalancing for nearly four years, this update aims to bring node-rdkafka in line with librdkafka capabilities and enhancing its functionality.
We use the code from this fork in our production environment for services that handle 5000 requests/messages per second. Using the cooperative-sticky partitioning strategy has shown good results by avoiding "stop-the-world" situations. Specifically, we have observed increased throughput and reduced spikes during scale-up and scale-down operations of pods in Kubernetes.
=> Cooperative Rebalance

lib/error.js
Fixes an existing issue https://github.com/Blizzard/node-rdkafka/issues/1117 caused by the removal of `util.isError`. `util.isError` was removed in Node.js v23 release, see https://github.com/nodejs/node/pull/52744
- Replaced util.isError(e) with instanceof Error and Object.prototype.toString.call(e) === '[object Error]'
- Ensured compatibility with Node.js v23
=> fix: remove deprecated util.isError usage

README.md, config.d.ts, errors.d.ts, lib/error.js, package-lock.json, package.json
Pull in https://github.com/confluentinc/librdkafka/releases/tag/v2.10.0
=> Update librdkafka to 2.10.0
